
language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

go_import_path: github.com/kit-x/gin-opencensus

script:
  - make travis-ci
after_success:
  - bash <(curl -s https://codecov.io/bash)